tjutDjango/tjut/urls.py
from django.conf.urls import url

from . import views

app_name = 'tjut'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search$', views.search, name='search'),
]

tjutDjango/tjutDjango/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tjut.urls')),
]

tjutDjango/tjut/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

tjutDjango/tjut/views.py
from django.http import HttpResponse
from django.shortcuts import render
import lucene
import pymysql.cursors

from lucene import getVMEnv,SimpleFragmenter,SimpleHTMLFormatter,QueryScorer,StringReader,QueryParser, IndexSearcher, ChineseAnalyzer, SimpleFSDirectory, File, VERSION, initVM, Version,Highlighter
#import jieba

initVM()
STORE_DIR='.././data/index'
directory = SimpleFSDirectory(File(STORE_DIR))
searcher = IndexSearcher(directory, True)
analyzer = ChineseAnalyzer(Version.LUCENE_CURRENT)

db_name='test'
user='root'
password='123456'

def index(request):
    return render(request,'tjut/index.html')


def search(request):

    vm_env = lucene.getVMEnv()
    vm_env.attachCurrentThread()
    
    ret={}
    maxLength=38

    search_content=request.GET.get('content')
    if len(search_content)>maxLength:
        pass

    query = QueryParser(Version.LUCENE_CURRENT, "contentKeyword",analyzer).parse(search_content)
    scoreDocs = searcher.search(query, 50).scoreDocs

    scorer = QueryScorer(query)
    formatter = SimpleHTMLFormatter("<span class=\"highlight\">", "</span>")
    highlighter = Highlighter(formatter,scorer)
    fragmenter = SimpleFragmenter(50)
    highlighter.setTextFragmenter(fragmenter)

    ret['NumOfDocs']=str(len(scoreDocs))+"total matching documents." 

    print ret['NumOfDocs']

    
    conn=pymysql.connect(   host='localhost',
                            user=user,
                            password=password,
                            db=db_name,
                            charset='utf8mb4',
                            cursorclass=pymysql.cursors.DictCursor)

    rst=''
    ret['search_list']=[]
    for scoreDoc in scoreDocs:
        doc = searcher.doc(scoreDoc.doc)
        _id=str(doc.get("id"))
        print _id
        sql='select * from webpage where id=%s'

        with conn.cursor() as cursor:
            cursor.execute(sql,(_id))
            rst=cursor.fetchone()
                
        titleStream = ChineseAnalyzer(Version.LUCENE_CURRENT).tokenStream("title", StringReader(rst['title']))
        titleFragment = highlighter.getBestFragment(titleStream, rst['title'])
        if titleFragment is None:
            titleFragment=rst['title']

        contentStream = ChineseAnalyzer(Version.LUCENE_CURRENT).tokenStream("content", StringReader(rst['content']))
        contentFragment = highlighter.getBestFragments(contentStream, rst['content'],5,'...')

        ret['search_list'].append({'title':titleFragment,'url':rst['url'],'content':contentFragment})
    #searcher.close()
    conn.close()

    return render(request,'tjut/result.html',{'search_list':ret['search_list'],'search_content':search_content})

tjutDjango/tjut/templates/tjut/index.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Engine</title>
        <link rel="stylesheet" type="text/css" href="{% static 'tjut/css/index.css' %}" />
    </head>
    <body>
        <br/><br/><br/><br/><br/><br/><br/><br/><br/>
        <div style="text-align:center;border;">
            <img src="{% static 'tjut/images/logo.png' %}" width="280" height="70" title="Engine">
            <form method="get" action="{% url 'tjut:search' %}">
            {% csrf_token %}
            <p>
                <input type="text" name="content" id="recid" placeholder="Search here..." required />
                <input type="submit" value="  Engine!  " id="subid"/>
            </p>
            </form>
        </div>
        <br/><br/><br/><br/><br/><br/><br/><br/><br/>
        <br/><br/><br/>
        <div style="text-align:center;border;">
            <p class="text_main">
              More information on papers ©2017 All Rights Reserved
              <!--More information on <a href="https://github.com/zhanglanqing/TinySearchEngine"  target="_blank"> Github </a>©2016 All Rights Reserved-->
            </p>
        </div>
    </body>
</html>

tjutDjango/tjut/templates/tjut/result.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv=”Content-Type” content=”text/html; charset=utf-8″ />
        <title>Engine</title>
        <link rel="stylesheet" type="text/css" href="{% static 'tjut/css/result.css' %}" />
    </head>
    <body>

            <img src="{% static 'tjut/images/logo.png' %}" width="140" height="35" title="Binoocle" style="float:left;">

            <form method="get" action="{% url 'tjut:search' %}">
            {% csrf_token %}
            <p>
                <input type="text" value="{{ search_content }}" name="content" id="recid" placeholder="Search here..." required />
                <input type="submit" value="  Engine!  " id="subid"/>
            </p>
            </form>

            <!--<a href="http://115.159.97.236:8080/Scheme" style="float:right;"><button>tiny-scheme-online-interpreter</button></a>-->

            <hr/>
            <br/><br/>

                {% load el_pagination_tags %}
				{% paginate search_list %}
				{% for item in search_list %}
                    <div class="null_er" style="float:left;">

                    </div>
                    <div class="box">
                    	<a href= "{{ item.url }}" target="_blank"> {{ item.title|safe|truncatewords_html:20 }} </a>
                        <p class="text_main">
                            {{ item.content|safe|truncatewords_html:45 }}
                        </p>
                        <p class="green_linker">
                            {{ item.url }}
                        </p>
                    </div>
                {% endfor %}
                <br/><br/><br/>
                <div class="null_er" style="float:left;">

                </div>
                <div class="box">
				{% show_pages %}
                </div>
                <div style="text-align:center;border;">
                <p class="text_main">
              	More information on papers ©2017 All Rights Reserved
              	</p>
                <!--<p class="text_main">
                  More information on <a href="https://github.com/zhanglanqing/TinySearchEngine"  target="_blank"> Github </a>©2016 All Rights Reserved
                </p>-->
                </div>
    </body>
</html>

tjutDjango/tjut/templates/tjut/test.html
<!DOCTYPE html>
<html>
<head>
    <title>TJUT Search</title>
</head>

<body>

<form class="form-wrapper cf">
  <input name='content' type="text" placeholder="Search here..." required>
  <button type="submit">Search</button>
</form>

</body>
</html>

<style type="text/css">
	body {
     background: #555 url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAB9JREFUeNpi/P//PwM6YGLAAuCCmpqacC2MRGsHCDAA+fIHfeQbO8kAAAAASUVORK5CYII=);
     font: 13px 'Lucida sans', Arial, Helvetica;
     color: #eee;
     text-align: center;
 }
 
 a {
     color: #ccc;
 }
 
 /*-------------------------------------*/
 
 .cf:before, .cf:after{
   content:"";
   display:table;
 }
 
 .cf:after{
   clear:both;
 }
 .cf{
   zoom:1;
 }
 /*-------------------------------------*/ 
 
 .form-wrapper {
     width: 450px;
     padding: 15px;
     margin: 150px auto 50px auto;
     background: #444;
     background: rgba(0,0,0,.2);
     -moz-border-radius: 10px;
     -webkit-border-radius: 10px;
     border-radius: 10px;
     -moz-box-shadow: 0 1px 1px rgba(0,0,0,.4) inset, 0 1px 0 rgba(255,255,255,.2);
     -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.4) inset, 0 1px 0 rgba(255,255,255,.2);
     box-shadow: 0 1px 1px rgba(0,0,0,.4) inset, 0 1px 0 rgba(255,255,255,.2);
 }
 
 .form-wrapper input {
     width: 330px;
     height: 20px;
     padding: 10px 5px;
     float: left;    
     font: bold 15px 'lucida sans', 'trebuchet MS', 'Tahoma';
     border: 0;
     background: #eee;
     -moz-border-radius: 3px 0 0 3px;
     -webkit-border-radius: 3px 0 0 3px;
     border-radius: 3px 0 0 3px;      
 }
 
 .form-wrapper input:focus {
     outline: 0;
     background: #fff;
     -moz-box-shadow: 0 0 2px rgba(0,0,0,.8) inset;
     -webkit-box-shadow: 0 0 2px rgba(0,0,0,.8) inset;
     box-shadow: 0 0 2px rgba(0,0,0,.8) inset;
 }
 
 .form-wrapper input::-webkit-input-placeholder {
    color: #999;
    font-weight: normal;
    font-style: italic;
 }
 
 .form-wrapper input:-moz-placeholder {
     color: #999;
     font-weight: normal;
     font-style: italic;
 }
 
 .form-wrapper input:-ms-input-placeholder {
     color: #999;
     font-weight: normal;
     font-style: italic;
 }    
 
 .form-wrapper button {
 overflow: visible;
     position: relative;
     float: right;
     border: 0;
     padding: 0;
     cursor: pointer;
     height: 40px;
     width: 110px;
     font: bold 15px/40px 'lucida sans', 'trebuchet MS', 'Tahoma';
     color: #fff;
     text-transform: uppercase;
     background: #d83c3c;
     -moz-border-radius: 0 3px 3px 0;
     -webkit-border-radius: 0 3px 3px 0;
     border-radius: 0 3px 3px 0;      
     text-shadow: 0 -1px 0 rgba(0, 0 ,0, .3);
 }   
   
 .form-wrapper button:hover{   
     background: #e54040;
 } 
   
 .form-wrapper button:active,
 .form-wrapper button:focus{   
     background: #c42f2f;    
 }
 
 .form-wrapper button:before {
     content: '';
     position: absolute;
     border-width: 8px 8px 8px 0;
     border-style: solid solid solid none;
     border-color: transparent #d83c3c transparent;
     top: 12px;
     left: -6px;
 }
 
 .form-wrapper button:hover:before{
     border-right-color: #e54040;
 }
 
 .form-wrapper button:focus:before{
     border-right-color: #c42f2f;
 }    
 
 .form-wrapper button::-moz-focus-inner {
     border: 0;
     padding: 0;
 }
</style>